services:
  db:
    environment:
      POSTGRES_DB: shoplite_staging
      POSTGRES_USER: shoplite_staging
      POSTGRES_PASSWORD: shoplite_staging_password
    volumes:
      - shoplite_pgdata_staging:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  api:
    environment:
      API_PORT: 3000
      DATABASE_URL: postgres://shoplite_staging:shoplite_staging_password@db:5432/shoplite_staging
      LOG_LEVEL: info
      APP_VERSION: staging

  proxy:
    ports:
      - "8081:80"

volumes:
  shoplite_pgdata_staging:
